# Generated by Django 5.2.4 on 2025-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_address_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='assets/person/def.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
