# Generated by Django 5.2.5 on 2025-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='assets/img/person/def.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
